### ISSUE TITLE
Premier atelier parisien

### ISSUE THREAD

**Issue by tdd** [nodeschool/paris#2]
Suivez cette *issue* pour être au courant de la date et du lieu du premier atelier. Sans doute fin janvier / début février 2015, idéalement chez Mozilla Paris, je confirme ça dès que possible.

**Comment by Murazaki** [comment]
Pour ce premier atelier, il y a une limite de 60 personnes, est-ce une limite fixe ? Je suis sur liste d'attente, dois-je attendre que des participants se désistent ?

**Comment by tdd** [comment]
Salut ! Heu tu sais meetup est une meilleure plate-forme pour nous contacter…  Comme ça les autres en profitent.

Oui, la limite est fixe, imposée par la capacité du lieu. Suite à l'annonce du groupe ce midi on s'est mangés 20 inscriptions en quelques minutes !  La liste d'attente est là justement pour que les désistements puissent profiter de façon automatique.

Bien à toi,

**Comment by Murazaki** [comment]
Salut !

Désolé, j'ai juste suivi les instructions sur la page de l'événement : "Des questions ? Des retours ? Envie d’aider ?
Ouvre une issue sur GitHub et viens nous en parler."

Merci pour ces précisions.

**Comment by tdd** [comment]
Ah mais oui tu as raison, au temps pour moi :smile:

Je pensais que tu venais directement de Meetup.com c'est pour ça.
