### ISSUE TITLE
Utilisation de la librairie ZLIB

### ISSUE THREAD

**Issue by y4nn0ff** [nodeschool/paris#4]
Bonjour,

J'essaie de décompresser un fichier zip, qui contient une liste de fichier via la librairie Zlib de node. 
En googolisant un peu, je remarque qu'adm-zip est plutôt utilisé, et que la doc sur zlib est très pauvre. 

J'aimerais savoir si vous avez un exemple de décompression de fichier zip (en mode sync, sans pipe) en utilisant la librairie zlib ?

A bientôt.
Yann

**Comment by githubtrainer** [comment]
Hello !

Je ne dirais pas qu'elle est pauvre… [Ce genre de partie](https://nodejs.org/api/zlib.html#zlib_examples) au début de la doc est pas mal…

Si la lib permet la compression/décompression brute de contenus, elle ne traite pas les structures de fichier internes (le catalogue de fichiers et dossiers dans un zip, par exemple). Pour des formats structurés, comme TAR ou Zip, on recourt à des modules tiers. Le module dominant pour Zip est, très logiquement… [`unzip`](https://www.npmjs.com/package/unzip).

Bien à toi,

**Comment by y4nn0ff** [comment]
Oui, bien sur les exemples sont top, si ce qu'on veut faire y est présent. Mais si on parle de la description des méthodes, c'est autre chose... bref ce n'est pas le sujet.

Merci pour ta réponse rapide, et clair ;). 

Entre temps je suis parti sur adm-zip qui fonctionne bien pour ce que j'ai à faire.

Bonne continuation.
