### ISSUE TITLE
Autres évènements ?

### ISSUE THREAD

**Issue by fraxken** [nodeschool/paris#6]
Bonjour,

J'ai vue que la dernière session à eu lieu en novembre 2016. D'autres sessions de prévu ?

Et autres questions, avez-vous des besoins en intervenant ? (Pour ma part cela va faire trois ans que je fais du NodeJS et partager ma connaissance sur le sujet m'intéresse énormément).

Cordialement,
Thomas

**Comment by MichaelTSS** [comment]
Hello @fraxken prochaine session prévue le 18 Mars prochain:
https://www.meetup.com/NodeSchool-Paris/events/235098700/

Meme si les RSVP sont complètes, tu peux venir. Il y a de la place à chaque fois.
